import './globals.css';
import { fontMontserrat, fontRighteous } from '@/fonts';
import { pageName } from '@/data';
import { getCategories, getOldWinners } from '@/services/firebaseService';
import StoreProvider from './StoreProvider';

export const metadata = {
  title: pageName,
  // description: 'Generated by create next app',
};
export default async function RootLayout({ children }: { children: any }) {
  const oldWinners = await getOldWinners();
  const categories = await getCategories();

  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fontMontserrat.variable} ${fontRighteous.variable} font-montserrat bg-slate-900 text-white`}
      >
        <StoreProvider
          initialState={{
            oldWinners,
            categories,
          }}
        >
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}

