import './globals.css';
import { fontMontserrat, fontRighteous } from '@/fonts';
import { pageName } from '@/data';
import { getInitialData } from '@/services/firebaseService';
import StoreProvider from './StoreProvider';

export const metadata = {
  title: pageName,
  // description: 'Generated by create next app',
};
export default async function RootLayout({ children }: { children: any }) {
  const initialData = await getInitialData();

  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fontMontserrat.variable} ${fontRighteous.variable} font-montserrat bg-slate-900 text-white`}
      >
        <StoreProvider initialState={initialData}>{children}</StoreProvider>
      </body>
    </html>
  );
}

