import './globals.css';
import { fontMontserrat, fontRighteous } from '@/fonts';
import { pageName } from '@/data';

export const metadata = {
  title: pageName,
  // description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fontMontserrat.variable} ${fontRighteous.variable} font-montserrat`}
      >
        {children}
      </body>
    </html>
  );
}

